### PR TITLE
Made Minor UI style improvements to the properties panel

### PR DESCRIPTION
**Pull request by SkyC0der**
### Description

Minor UI style improvements to the properties panel
### What is the purpose of this pull request? 

- [ ] New feature
- [ ] Documentation update
- [x] Bug fix
- [ ] Refactor
- [ ] Other

### CODE REVIEW

**Comment by Kitenite** [comment]
It looks good to me but deferring to @drfarrell for the final design pass 👍

**Comment by drfarrell** [comment]
> It looks good to me but deferring to @drfarrell for the final design pass 👍 Great stuff!

The inputs and radii look good now – I also tightened some of the gaps between inputs to be more consistent

**Comment by SkyC0der** [comment]
how do I resolve the merge conflict?

**Comment by drfarrell** [comment]
> how do I resolve the merge conflict?

I think @Kitenite is taking a look at it in a bit but we should be good to go later today 😎

**Comment by Kitenite** [comment]
Looks awesome, great work @SkyC0der !

**Pull request merged**
